export const tasks = [
  {
    id: 1,
    title: "Video Player is not working",
    label: "Bug",
    assignedTo: "Vikash",
    status: "todo",
  },
  {
    id: 2,
    title: "Login UI is incorrect",
    label: "Feature",
    assignedTo: "Shiva",
    status: "todo",
  },
  {
    id: 3,
    title: "Optimize image loading",
    label: "Improvement",
    assignedTo: "Alok",
    status: "todo",
  },
  {
    id: 4,
    title: "Fix CSS issues on the dashboard",
    label: "Bug",
    assignedTo: "Vikash",
    status: "in-progress",
  },
  {
    id: 5,
    title: "Implement dark mode",
    label: "Feature",
    assignedTo: "Shiva",
    status: "in-progress",
  },
  {
    id: 6,
    title: "Refactor codebase",
    label: "Improvement",
    assignedTo: "Alok",
    status: "in-progress",
  },
  {
    id: 7,
    title: "Add unit tests",
    label: "Bug",
    assignedTo: "Vikash",
    status: "done",
  },
  {
    id: 8,
    title: "Update documentation",
    label: "Feature",
    assignedTo: "Shiva",
    status: "done",
  },
  {
    id: 9,
    title: "Improve performance",
    label: "Improvement",
    assignedTo: "Alok",
    status: "done",
  },
];
